[server]
maxUploadSize = 500



[theme]

primaryColor = "#f5b77dff"
backgroundColor = "#e7f5e3ff"
secondaryBackgroundColor = "#effaebff"
textColor = "#31333f"

redColor = "#ff4b4b"
orangeColor = "#ff8700"
yellowColor = "#faca2b"
blueColor = "#1c83e1"
greenColor = "#21c354"
violetColor = "#803df5"
grayColor = "#a3a8b8"


linkColor = "#1c83e1"
linkUnderline = true

codeTextColor = "#21c354"
codeBackgroundColor = "#f0f0f0"



font="Urbanist:https://fonts.googleapis.com/css2?family=Urbanist:wght@400;600&display=swap"
headingFont="Urbanist:https://fonts.googleapis.com/css2?family=Urbanist:wght@800&display=swap"




baseRadius = "0.5rem"
buttonRadius = "0.5rem"

borderColor = "#e0e0e0"
dataframeBorderColor = "#d0d0d0"
dataframeHeaderBackgroundColor = "#f0f0f0"
showWidgetBorder = true
showSidebarBorder = true

chartCategoricalColors = ["#1c83e1", "#83c9ff", "#ff2b2b", "#ffabab", "#29b09d", "#7defa1", "#ff8700", "#ffd16a", "#6d3fc0", "#d5dae5"]
chartSequentialColors = ["#e4f5ff", "#c7ebff", "#a6dcff", "#83c9ff", "#60b4ff", "#3d9df3", "#1c83e1", "#0068c9", "#0054a3", "#004280"]


[theme.sidebar]

backgroundColor = '#effaebff'
textColor = '#31333f'
borderColor = '#a0c090'
showWidgetBorder = true