[server]
maxUploadSize = 500

[theme]
primaryColor = "#f5b77dff"
backgroundColor = "#e7f5e3ff"
secondaryBackgroundColor = "#effaebff"
textColor = "#31333f"

font="Urbanist:https://fonts.googleapis.com/css2?family=Urbanist:wght@400;600&display=swap"
headingFont="Urbanist:https://fonts.googleapis.com/css2?family=Urbanist:wght@800&display=swap"

[theme.sidebar]
backgroundColor = '#658359ff'
textColor = '#ffffffff'
borderColor = '#a0c090'
showWidgetBorder = true